use_frameworks!

platform :ios, '10.0'

target 'degpeg-video-call-ios-sdk_Example' do
  pod 'degpeg-video-call-ios-sdk', :path => '../'

  target 'degpeg-video-call-ios-sdk_Tests' do
    inherit! :search_paths

    
  end
end
